# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  REGISTRY_NAME: registry.rednaw.nl
  IMAGE_NAME: rednaw/hello-world

includes:
  iac:
    taskfile: ../iac/tasks/Taskfile.app.yml

tasks:
  default:
    cmds:
      - task: iac:default
